### ISSUE TITLE
Can't login through Github, email not linked

### ISSUE THREAD

**Issue by nineinchnick** [samdark/yiifeed#17]
When trying to log in using Github I get the following error:

> User with the same email as in GitHub account already exists but isn't linked to it. Login using email first to link it. 

I tried the Github link on the _signup_ page and got the same error.

I tried to recover my password and it said there's no such account (using my email).

Then I registered and tried to login again and still same error.

Then I logged in with my username and went to my profile and tried to link to Github and still got same error.

**Comment by samdark** [comment]
The only place where such error is thrown: https://github.com/samdark/yiifeed/blob/master/controllers/SiteController.php#L92

**Comment by samdark** [comment]
Is your GitHub email set to private or left empty?

**Comment by nineinchnick** [comment]
No, it's not.

**Comment by samdark** [comment]
Weird...
