### ISSUE TITLE
Failed to login using GitHub

### ISSUE THREAD

**Issue by SilverFire** [samdark/yiifeed#19]
When I try to login or signup using GitHub account, I get the error:
`User with the same email as in GitHub account already exists but isn't linked to it. Login using email first to link it.`

When I try to reset my password, I enter my GitHub email and get error: `There is no user with such email.`

**Comment by samdark** [comment]
What are your GitHub email privacy settings? https://github.com/settings/emails

**Comment by SilverFire** [comment]
It is public

**Comment by samdark** [comment]
Should be OK now.

**Comment by samdark** [comment]
https://github.com/samdark/yiifeed/commit/8fc6bc6c2b92f2fd7426b4a2dbb4a1a32d963bc6

**Comment by SilverFire** [comment]
It is OK not, thank you

**Comment by samdark** [comment]
Not?

**Comment by SilverFire** [comment]
Now*
