### ISSUE TITLE
Voting

### ISSUE THREAD

**Issue by samdark** [samdark/yiifeed#2]
- [ ] Each news could be up/down voted.
- [ ] Vote could be changed any number of times.
- [ ] Total is displyayed in news.
- [ ] News with better rating are marked with color, news with bad rating are greyed out.

**Comment by Chiliec** [comment]
Александр, я как раз похожее расширение сделал, может подойдет? Правда его нужно интернационализировать и по качеству кода всё плохо :) Выглядит примерно так:
![Vote](https://cloud.githubusercontent.com/assets/982358/5598488/22e3311c-92d9-11e4-82df-b3708fbf7fc4.png)
https://github.com/Chiliec/yii2-vote

**Comment by Chiliec** [comment]
Сделал интернационализацию, надеюсь воспользуетесь :octocat:

**Comment by samdark** [comment]
Посмотрю обязательно.

**Comment by samdark** [comment]
Decided not to implement it.
