### ISSUE TITLE
There is an error on http://yiifeed.com/

### ISSUE THREAD

**Issue by b17** [samdark/yiifeed#33]
After footer:
![selection_002](https://cloud.githubusercontent.com/assets/2056667/18608699/1f48fd1e-7cf9-11e6-9b84-811ad5bdfe28.jpg)

**Comment by samdark** [comment]
I don't have it. Which browser is used? Which page is that? What's the URL?

**Comment by b17** [comment]
Currently, the error is missing. 

Browser: 52.0.2743.116 Built on Ubuntu
Url: http://yiifeed.com/

I don't know the cause of the error. If I get some information, I'll update the issue.

**Comment by samdark** [comment]
OK. Closing it till then.
