### ISSUE TITLE
Add direct link to the article on main feed (without entering yiifeed news itself)? 

### ISSUE THREAD

**Issue by raiym** [samdark/yiifeed#34]

**Comment by cebe** [comment]
can you elaborate? I do not understand the problem. RSS contains link to the article.

**Comment by samdark** [comment]
He means news list on the front page.

**Comment by raiym** [comment]
Main Page without source: 

![mainpage](https://cloud.githubusercontent.com/assets/5698585/19155569/037aa366-8bf0-11e6-9c3b-da40b38d90f6.png)

Article with source: 

![newsitself](https://cloud.githubusercontent.com/assets/5698585/19155570/03847e9a-8bf0-11e6-9b6f-8525f75ac040.png)

**Comment by samdark** [comment]
Since there are comments in the article view, it would make sense to add "comment" button leading there and displaying number of these comments.

**Comment by raiym** [comment]
Just to be clear I made image to be sure we are talking about same things (sorry for quality): 

![feed](https://cloud.githubusercontent.com/assets/5698585/19156547/5232a92e-8bf3-11e6-8f6e-60c9ac09084f.png)

If so isn't comment link feature separate issue?

**Comment by samdark** [comment]
Comment link makes sense if we're adding direct link to article source right to the front page and isn't necessary otherwise.

**Comment by samdark** [comment]
Not going to change it.
