### ISSUE TITLE
Professional design

### ISSUE THREAD

**Issue by samdark** [samdark/yiifeed#36]
Current design is a standard bootstrap template plus some effort by myself. It's not really good so if you can contribute professionally on this matter, please comment.

**Comment by samdark** [comment]
In progress. Mocks will be published here when done.

**Comment by samdark** [comment]
Here they are: https://github.com/samdark/yiifeed-redesign

**Comment by naffiq** [comment]
@samdark 

Need any help with markup?

**Comment by samdark** [comment]
Yes.
