### ISSUE TITLE
Error (#8) after signup

### ISSUE THREAD

**Issue by schmunk42** [samdark/yiifeed#4]
I got this error after signup

![bildschirmfoto 2014-12-28 um 01 43 37](https://cloud.githubusercontent.com/assets/649031/5562700/fc367132-8e32-11e4-8d21-346e7cc78d80.png)

Login and account seem to work fine though.

**Comment by samdark** [comment]
Fixed. The issue was that GitHub isn't giving you email for some profiles and I was counting on it.
